# Generated by Django 6.0.6 on 2026-07-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='current_address',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='selfie_url',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='alumniprofile',
            name='willing_to_mentor',
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
