# Generated by Django 6.0.6 on 2026-07-03 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_simplify_profile_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnieditrequest',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='alumnieditrequest',
            name='reviewed_by',
        ),
        migrations.RemoveIndex(
            model_name='otp',
            name='alumni_otp_created_41b31d_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_coordinator',
        ),
        migrations.DeleteModel(
            name='AlumniEditRequest',
        ),
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
