# Generated by Django 6.0.6 on 2026-07-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_remove_otp_and_editrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
