# Generated by Django 6.0.6 on 2026-07-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_add_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumniprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='free_to_talk_days',
            field=models.CharField(blank=True, help_text='e.g., Weekends, Monday-Friday evenings', max_length=200),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='native_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='nature_of_profession',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='support_offered',
            field=models.TextField(blank=True, help_text='Area of experience, networks, market, etc.'),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='visit_frequency_coimbatore',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('rarely', 'Rarely'), ('never', 'Never')], max_length=50),
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='willing_to_mentor',
            field=models.BooleanField(default=False, help_text='Willing to associate and support batchmates through networks'),
        ),
    ]
