# Generated by Django 6.0.6 on 2026-07-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_alumniprofile_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='designation',
        ),
    ]
