# Generated by Django 6.0.6 on 2026-07-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_remove_alumniprofile_designation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumniprofile',
            name='nature_of_profession',
        ),
        migrations.AddField(
            model_name='alumniprofile',
            name='support_mode',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline')], help_text='Mode of support — Online or Offline', max_length=20),
        ),
    ]
