# Generated by Django 6.0.6 on 2026-07-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_remove_alumniprofile_nature_of_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniprofile',
            name='support_mode',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline'), ('both', 'Both Online & Offline'), ('not_possible', 'Not Possible')], help_text='Mode of support — Online, Offline, Both, or Not Possible', max_length=20),
        ),
    ]
